name: Build, analyze and test the project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build, analyze and test
    runs-on: windows-latest
    timeout-minutes: 100
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Set up JDK 17 for SonarCloud scanner
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.

      - name: Install SonarCloud scanner
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      # The "upload sarif" action is unable to upload the report as property
      # "repositoryUri" contains a trailing newline: "https://github.com/giuse94/PSDX\r\n".
      # - name: Install ReSharper CLI tools
      #  run: dotnet tool install --global JetBrains.ReSharper.GlobalTools
          
      - name: Install .NET Coverage tool
        run: dotnet tool install --global dotnet-coverage

      - name: Install ReportGenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Install Stryker Mutator tool
        run: dotnet tool install --global dotnet-stryker

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and test with SonarCloud scanner wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"giuse94_PSDX" /o:"giuse94" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"
          dotnet build --no-restore
          dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # - name: Perform ReSharper analysis
      #  run: jb inspectcode -f="sarif" -o="resharper-report.sarif" --swea --no-build "PSDX.sln"

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "CodeQL"

      - name: Generate coverage report
        run: reportgenerator -reports:coverage.xml -targetdir:CoverageReport -reporttypes:Html

      - name: Run mutation tests
        run: dotnet stryker --reporter "html" --output "MutationReport"

      # - name: Upload ReSharper report file
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    sarif_file: resharper-report.sarif

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: |
            CoverageReport
            MutationReport
